// apps/tanstack/src/routes/_public/-the-footer.tsx
import { Button } from "@niama/ui/react/button";
import { THE_FOOTER } from "@niama/ui/shared/the-footer";
import { Link } from "@tanstack/react-router";
import { IconButton } from "@/components/icon-button";
import type { ReadPublicLayoutProps } from "@/lib/layouts";

// MAIN ------------------------------------------------------------------------------------------------------------------------------------
export const TheFooter = ({ socials }: Pick<ReadPublicLayoutProps, "socials">) => (
  <footer className={THE_FOOTER.base()}>
    <Button className={THE_FOOTER.disclaimer()} nativeButton={false} render={<Link to="/" />} variant="outline">
      Mentions Légales
    </Button>
    <div className={THE_FOOTER.socials()}>
      {socials.map(({ href, icon, key, label }) => (
        <IconButton
          className={THE_FOOTER.social()}
          icon={icon}
          key={key}
          label={label}
          nativeButton={false}
          render={<a href={href} rel="noopener" target="_blank" />}
          size="icon"
          variant="outline"
        />
      ))}
    </div>
  </footer>
);

// apps/sveltekit/src/lib/components/the-footer.svelte
<script lang="ts">
  import type { ReadPublicLayoutProps } from "@niama/domain/functions/layouts";
  import { THE_FOOTER } from "@niama/ui/shared/the-footer";
  import { Button } from "@niama/ui/svelte/button";

  let { socials }: Pick<ReadPublicLayoutProps, "socials"> = $props();
</script>

<footer class={THE_FOOTER.base()}>
  <Button class={THE_FOOTER.disclaimer()} href="/" variant="outline">Mentions Légales</Button>
  <div class={THE_FOOTER.socials()}>
    {#each socials as social (social.key)}
      <Button
        aria-label={social.label}
        class={THE_FOOTER.social()}
        href={social.href}
        rel="noopener"
        size="icon"
        target="_blank"
        variant="outline"
      >
        <span class={social.icon}></span>
      </Button>
    {/each}
  </div>
</footer>
