// packages/ui-svelte/src/components/ui/carousel/carousel-next.svelte
<script lang="ts" module>
  import type { ButtonProps } from "@niama/ui-svelte/ui/button";
  import type { WithoutChildren } from "bits-ui";

  export type CarouselNextProps = WithoutChildren<ButtonProps>;
</script>

<script lang="ts">
  import { CAROUSEL } from "@niama/ui/carousel";
  import { cn } from "@niama/ui-svelte/lib/utils";
  import { Button } from "@niama/ui-svelte/ui/button";
  import { useSelector } from "@tanstack/svelte-store";
  import { getEmblaContext } from "./context";

  let { ref = $bindable(null), class: className, variant = "outline", size = "icon-sm", ...restProps }: CarouselNextProps = $props();

  const { store: carouselStore } = getEmblaContext();
  const canGoToNext = useSelector(carouselStore, (state) => state.canGoToNext);
  const api = useSelector(carouselStore, (state) => state.api);
</script>

<Button
  data-slot="carousel-next"
  {variant}
  {size}
  class={cn(CAROUSEL.next(), className)}
  disabled={!canGoToNext.current}
  onclick={() => api.current?.goToNext()}
  bind:ref
  {...restProps}
>
  <span class="icon-[tabler--chevron-right]"></span>
  <span class="sr-only">Suivant</span>
</Button>

// packages/ui/src/components/react/carousel.tsx
import { createStoreContext, type Store, useSelector } from "@tanstack/react-store";
import useEmblaCarousel, { type EmblaRootNodeRefType } from "embla-carousel-react";
import { useEffect } from "react";
import { cn } from "../../lib/utils";
import { CAROUSEL, type CarouselActions, type CarouselState } from "../shared/carousel";
import { Button } from "./button";

// CONTEXT ---------------------------------------------------------------------------------------------------------------------------------
const { StoreProvider: CarouselProvider, useStoreContext: useCarousel } = createStoreContext<CarouselContextProps>();

type CarouselContextProps = { ref: EmblaRootNodeRefType; store: Store<CarouselState, CarouselActions> };

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function Carousel({ store, className, children, ...rest }: CarouselProps) {
  const opts = useSelector(store, (state) => state.opts);
  const plugins = useSelector(store, (state) => state.plugins);
  const [ref, api] = useEmblaCarousel(opts, plugins);

  useEffect(() => (api ? store.actions.bindApi(api) : undefined), [api, store]);

  return (
    <CarouselProvider value={{ ref, store }}>
      <section
        aria-roledescription="carousel"
        className={cn(CAROUSEL.base(), className)}
        data-axis={opts.axis ?? "x"}
        data-slot="carousel"
        onKeyDownCapture={store.actions.handleKeydown}
        role="region"
        {...rest}
      >
        {children}
      </section>
    </CarouselProvider>
  );
}
export type CarouselProps = React.ComponentProps<"section"> & Pick<CarouselContextProps, "store">;

// CONTENT ---------------------------------------------------------------------------------------------------------------------------------
export function CarouselContent({ className, viewportClassName, ...props }: CarouselContentProps) {
  const { ref } = useCarousel();

  return (
    <div className={cn(CAROUSEL.viewport(), viewportClassName)} data-slot="carousel-content" ref={ref}>
      <div className={cn(CAROUSEL.content(), className)} {...props} />
    </div>
  );
}
export type CarouselContentProps = React.ComponentProps<"div"> & { viewportClassName?: string };

// ITEM ------------------------------------------------------------------------------------------------------------------------------------
export function CarouselItem({ className, ...props }: CarouselItemProps) {
  return <section className={cn(CAROUSEL.item(), className)} data-slot="carousel-item" {...props} />;
}
export type CarouselItemProps = React.ComponentProps<"section">;

// NEXT ------------------------------------------------------------------------------------------------------------------------------------
export function CarouselNext({ className, variant = "outline", size = "icon-sm", ...props }: CarouselNextProps) {
  const { store } = useCarousel();
  const { api, canGoToNext } = useSelector(store, (state) => state);

  return (
    <Button
      className={cn(CAROUSEL.next(), className)}
      data-slot="carousel-next"
      disabled={!canGoToNext}
      onClick={() => api?.goToNext()}
      size={size}
      variant={variant}
      {...props}
    >
      <span className="icon-[tabler--chevron-right]" />
      <span className="sr-only">Suivant</span>
    </Button>
  );
}
export type CarouselNextProps = Omit<React.ComponentProps<typeof Button>, "className"> & { className?: string };

// PREVIOUS --------------------------------------------------------------------------------------------------------------------------------
export function CarouselPrevious({ className, variant = "outline", size = "icon-sm", ...props }: CarouselPreviousProps) {
  const { store } = useCarousel();
  const { api, canGoToPrev } = useSelector(store, (state) => state);

  return (
    <Button
      className={cn(CAROUSEL.previous(), className)}
      data-slot="carousel-previous"
      disabled={!canGoToPrev}
      onClick={() => api?.goToPrev()}
      size={size}
      variant={variant}
      {...props}
    >
      <span className="icon-[tabler--chevron-left]" />
      <span className="sr-only">Précédent</span>
    </Button>
  );
}
export type CarouselPreviousProps = Omit<React.ComponentProps<typeof Button>, "className"> & { className?: string };
