// packages/ui/src/components/svelte/section/section.svelte
<script lang="ts" module>
  import type { WithElementRef } from "@niama/ui/lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  export type SectionProps = WithElementRef<HTMLAttributes<HTMLElement>> & {
    class?: string;
    description?: string;
    id: string;
    title?: string;
    withSeparator?: boolean;
  };
</script>

<script lang="ts">
  import { cn } from "@niama/ui/lib/utils";
  import { SECTION } from "@niama/ui/shared/section";
  import { Separator } from "@niama/ui/svelte/separator";

  let {
    ref = $bindable(null),
    children,
    class: className = "",
    description,
    id,
    title,
    withSeparator = false,
    ...restProps
  }: SectionProps = $props();
</script>

<section bind:this={ref} data-section class={cn(SECTION.base({ className }))} {id} {...restProps}>
  {#if withSeparator}
    <Separator class={SECTION.separator()} orientation="vertical" />
  {/if}
  {#if title}
    <h2 class={SECTION.title()}>{title}</h2>
  {/if}
  {#if description}
    <p class={SECTION.description()}>{description}</p>
  {/if}
  {@render children?.()}
</section>

// packages/ui/src/components/react/section.tsx
import { cn } from "@niama/ui/lib/utils";
import { SECTION } from "@niama/ui/shared/section";
import { Separator } from "./separator";

// MAIN ------------------------------------------------------------------------------------------------------------------------------------
export function Section({ children, className, description, id, title, withSeparator }: SectionProps) {
  return (
    <section className={cn(SECTION.base(), className)} data-section id={id}>
      {withSeparator && <Separator className={SECTION.separator()} orientation="vertical" />}
      {title && <h2 className={SECTION.title()}>{title}</h2>}
      {description && <p className={SECTION.description()}>{description}</p>}
      {children}
    </section>
  );
}
export type SectionProps = React.ComponentProps<"section"> & { description?: string; id: string; title?: string; withSeparator?: boolean };
