// apps/tanstack-react/src/routes/_public/index.tsx
import { readIndexPage } from "@niama/domain/functions/pages";
import { ContactForm } from "@niama/ui/react/contact-form";
import { Separator } from "@niama/ui/react/separator";
import { INDEX_PAGE, updateHash } from "@niama/ui/shared/index-page";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect } from "react";
import { toast } from "sonner";
import { AttendantsCarousel } from "@/components/attendants/carousel";
import { DisciplinesCarousel } from "@/components/disciplines/carousel";
import { Section } from "@/components/section";
import { createContact } from "@/functions/form";

// ROUTE -----------------------------------------------------------------------------------------------------------------------------------
export const Route = createFileRoute("/_public/")({
  component: IndexPage,
  loader: () => readIndexPage(),
});

// PAGE ------------------------------------------------------------------------------------------------------------------------------------
function IndexPage() {
  const navigate = useNavigate();
  const { attendants, contact, disciplines, hero } = Route.useLoaderData();

  useEffect(() => updateHash((hash) => navigate({ to: "/", hash, replace: true, hashScrollIntoView: false })), [navigate]);

  return (
    <div className={INDEX_PAGE.base()}>
      <Section className={INDEX_PAGE.hero()} id="top-3">
        <div className={INDEX_PAGE.heroContent()}>
          <h1 className={INDEX_PAGE.heroTitle()}>{hero.title}</h1>
          <p className={INDEX_PAGE.heroDescription()}>{hero.description}</p>
        </div>
      </Section>
      <Section id="les-voies" {...disciplines} withSeparator>
        <DisciplinesCarousel {...disciplines} />
      </Section>
      <Section id="les-accompagnants" {...attendants} withSeparator>
        <AttendantsCarousel {...attendants} />
      </Section>
      <Section id="contact" {...contact} withSeparator>
        <ContactForm
          onSubmit={async (value) => await createContact({ data: value })}
          onSuccess={() => toast.success("Merci de votre intérêt ! Nous reviendrons vers vous très bientôt.")}
        />
        <Separator className="self-center! mb-34 h-24" orientation="vertical" />
      </Section>
    </div>
  );
}

// apps/tanstack-solid/src/routes/_public/index.tsx
import { readIndexPage } from "@niama/domain/functions/pages";
import { INDEX_PAGE, nativeHashUpdater, updateHash } from "@niama/ui/shared/index-page";
import { createFileRoute } from "@tanstack/solid-router";
import { onSettled } from "solid-js";
import { AttendantsCarousel } from "@/components/attendants/carousel";
import { DisciplinesCarousel } from "@/components/disciplines/carousel";
import { Section } from "@/components/section";
import { Separator } from "@/components/separator";
// import { ContactForm } from "./index/-contact-form";

export const Route = createFileRoute("/_public/")({
  component: IndexPage,
  loader: () => readIndexPage(),
});

function IndexPage() {
  const data = Route.useLoaderData();
  const { attendants, contact, disciplines, hero } = data();

  onSettled(() => updateHash(nativeHashUpdater));

  return (
    <div class={INDEX_PAGE.base()}>
      <Section class={INDEX_PAGE.hero()} id="top-3">
        <div class={INDEX_PAGE.heroContent()}>
          <h1 class={INDEX_PAGE.heroTitle()}>{hero.title}</h1>
          <p class={INDEX_PAGE.heroDescription()}>{hero.description}</p>
        </div>
      </Section>
      <Section id="les-voies" {...disciplines} withSeparator>
        <DisciplinesCarousel items={disciplines.items} />
      </Section>
      <Section id="les-accompagnants" {...attendants} withSeparator>
        <AttendantsCarousel items={attendants.items} />
      </Section>
      <Section id="contact" {...contact} withSeparator>
        {/* <ContactForm /> */}
        <Separator class="self-center! mb-34 h-24" orientation="vertical" />
      </Section>
    </div>
  );
}
