// apps/tanstack-solid/src/components/badge.tsx
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@niama/ui/lib/utils";
import type { JSX } from "solid-js";

const BADGE = cva(
  `group/badge inline-flex h-5 w-fit shrink-0 items-center justify-center gap-1 overflow-hidden whitespace-nowrap rounded-4xl border 
	border-transparent px-2 py-0.5 font-medium text-xs transition-all 
	focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 
	has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 
	aria-invalid:border-destructive aria-invalid:ring-destructive/20 
	dark:aria-invalid:ring-destructive/40 
	[&>svg]:pointer-events-none [&>svg]:size-3!`,
  {
    variants: {
      variant: {
        default: `bg-primary text-primary-foreground 
					[a]:hover:bg-primary/80`,
        secondary: `bg-secondary text-secondary-foreground 
					[a]:hover:bg-secondary/80`,
        destructive: `bg-destructive/10 text-destructive 
					focus-visible:ring-destructive/20 
					dark:bg-destructive/20 dark:focus-visible:ring-destructive/40 
					[a]:hover:bg-destructive/20`,
        outline: `border-border bg-input/30 text-foreground 
					[a]:hover:bg-muted [a]:hover:text-muted-foreground`,
        ghost: `hover:bg-muted hover:text-muted-foreground 
					dark:hover:bg-muted/50`,
        link: `text-primary underline-offset-4 
					hover:underline`,
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
);

export function Badge(props: BadgeProps) {
  const { class: className, variant = "default", ...rest } = props;
  return <span class={cn(BADGE({ variant }), className)} data-slot="badge" {...rest} />;
}

export type BadgeProps = JSX.HTMLAttributes<HTMLSpanElement> &
  VariantProps<typeof BADGE> & {
    class?: string;
  };

// packages/ui-svelte/src/components/badge/badge.svelte
<script lang="ts" module>
  import { tv, type VariantProps } from "tailwind-variants";

  export const badgeVariants = tv({
    base: "group/badge inline-flex h-5 w-fit shrink-0 items-center justify-center gap-1 overflow-hidden whitespace-nowrap rounded-4xl border border-transparent px-2 py-0.5 font-medium text-xs transition-all transition-colors focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none [&>svg]:size-3!",
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground [a]:hover:bg-primary/80",
        secondary: "bg-secondary text-secondary-foreground [a]:hover:bg-secondary/80",
        destructive:
          "bg-destructive/10 text-destructive focus-visible:ring-destructive/20 dark:bg-destructive/20 dark:focus-visible:ring-destructive/40 [a]:hover:bg-destructive/20",
        outline: "border-border text-foreground [a]:hover:bg-muted [a]:hover:text-muted-foreground",
        ghost: "hover:bg-muted hover:text-muted-foreground dark:hover:bg-muted/50",
        link: "text-primary underline-offset-4 hover:underline",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  });

  export type BadgeVariant = VariantProps<typeof badgeVariants>["variant"];
</script>

<script lang="ts">
  import { cn, type WithElementRef } from "@niama/ui-svelte/lib/utils";
  import type { HTMLAnchorAttributes } from "svelte/elements";

  let {
    ref = $bindable(null),
    href,
    class: className,
    variant = "default",
    children,
    ...restProps
  }: WithElementRef<HTMLAnchorAttributes> & {
    variant?: BadgeVariant;
  } = $props();
</script>

<svelte:element
  this={href ? "a" : "span"}
  bind:this={ref}
  data-slot="badge"
  {href}
  class={cn(badgeVariants({ variant }), className)}
  {...restProps}
>
  {@render children?.()}
</svelte:element>
