// apps/sveltekit/src/lib/components/disciplines/badge.svelte
<script lang="ts">
  import type { Disciplines } from "@niama/domain/functions/disciplines";
  import { readDisciplineBySlug } from "@niama/domain/functions/disciplines";
  import { DISCIPLINES_BADGE } from "@niama/ui/disciplines/badge";
  import { cn } from "@niama/ui-svelte/lib/utils";
  import { Badge } from "@niama/ui-svelte/ui/badge";

  let { class: className = "", slug }: { class?: string; slug: Disciplines["Entity"]["slug"] } = $props();

  const discipline = $derived(readDisciplineBySlug(slug));
</script>

<Badge class={cn(DISCIPLINES_BADGE(), className)} data-discipline={slug}>{discipline.title}</Badge>

// apps/tanstack-react/src/components/disciplines/badge.tsx
import { type Disciplines, readDisciplineBySlug } from "@niama/domain/functions/disciplines";
import { DISCIPLINES_BADGE } from "@niama/ui/disciplines/badge";
import { cn } from "@niama/ui/lib/utils";
import { Badge, type BadgeProps } from "@niama/ui-react/badge";

// MAIN ------------------------------------------------------------------------------------------------------------------------------------
export const DisciplinesBadge = ({ className, slug, ...props }: DisciplinesBadgeProps) => {
  const { title } = readDisciplineBySlug(slug);
  return (
    <Badge {...props} className={cn(DISCIPLINES_BADGE(), className)} data-discipline={slug}>
      {title}
    </Badge>
  );
};
type DisciplinesBadgeProps = BadgeProps & { slug: Disciplines["Entity"]["slug"] };
