// packages/ui/src/components/react/button.tsx
import { Button as ButtonPrimitive } from "@base-ui/react/button";
import { cn } from "@niama/ui/lib/utils";
import { BUTTON, type ButtonStyles } from "@niama/ui/shared/button";

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function Button({ className, variant = "default", size = "default", ...props }: ButtonProps) {
  return <ButtonPrimitive className={cn(BUTTON({ variant, size }), className)} data-slot="button" {...props} />;
}
export type ButtonProps = Omit<ButtonPrimitive.Props, "className"> & ButtonStyles & { className?: string };

// apps/tanstack-solid/src/components/button.tsx
import { BUTTON, type ButtonStyles } from "@niama/ui/shared/button";
import { cn } from "@niama/ui/lib/utils";
import type { JSX } from "solid-js";

export function Button(props: ButtonProps) {
  const {
    class: className,
    ref,
    size = "default",
    type = "button",
    variant = "default",
    ...rest
  } = props;

  return <button ref={ref} class={cn(BUTTON({ size, variant }), className)} type={type} {...rest} />;
}

export type ButtonProps = JSX.ButtonHTMLAttributes<HTMLButtonElement> &
  ButtonStyles & {
    class?: string;
    ref?: HTMLButtonElement | ((el: HTMLButtonElement) => void);
  };
