// packages/ui-react/src/components/ui/button.tsx
import { Button as ButtonPrimitive } from "@base-ui/react/button";
import { BUTTON, type ButtonStyles } from "@niama/ui/button";
import { cn } from "@niama/ui-react/lib/utils";

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function Button({ className, variant = "default", size = "default", ...props }: ButtonProps) {
  return <ButtonPrimitive className={cn(BUTTON({ variant, size }), className)} data-slot="button" {...props} />;
}
export type ButtonProps = Omit<ButtonPrimitive.Props, "className"> & ButtonStyles & { className?: string };

// apps/tanstack-solid/src/components/button.tsx
import { BUTTON, type ButtonStyles } from "@niama/ui/button";
import { cn } from "@niama/ui/lib/utils";
import type { JSX } from "solid-js";

export function Button(props: ButtonProps) {
  const { class: className, ref, size = "default", type = "button", variant = "default", ...rest } = props;

  return <button class={cn(BUTTON({ size, variant }), className)} ref={ref} type={type} {...rest} />;
}

export type ButtonProps = JSX.ButtonHTMLAttributes<HTMLButtonElement> &
  ButtonStyles & {
    class?: string;
    ref?: HTMLButtonElement | ((el: HTMLButtonElement) => void);
  };
