// packages/ui-react/src/raw/card.tsx
import * as React from "react"

import { cn } from "@niama/ui/lib/utils"

function Card({
  className,
  size = "default",
  ...props
}: React.ComponentProps<"div"> & { size?: "default" | "sm" }) {
  return (
    <div
      data-slot="card"
      data-size={size}
      className={cn(
        "group/card flex flex-col gap-6 overflow-hidden rounded-2xl bg-card py-6 text-sm text-card-foreground ring-1 ring-foreground/10 has-[>img:first-child]:pt-0 data-[size=sm]:gap-4 data-[size=sm]:py-4 *:[img:first-child]:rounded-t-xl *:[img:last-child]:rounded-b-xl",
        className
      )}
      {...props}
    />
  )
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-header"
      className={cn(
        "group/card-header @container/card-header grid auto-rows-min items-start gap-2 rounded-t-xl px-6 group-data-[size=sm]/card:px-4 has-data-[slot=card-action]:grid-cols-[1fr_auto] has-data-[slot=card-description]:grid-rows-[auto_auto] [.border-b]:pb-6 group-data-[size=sm]/card:[.border-b]:pb-4",
        className
      )}
      {...props}
    />
  )
}

function CardTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-title"
      className={cn("font-heading text-base font-medium", className)}
      {...props}
    />
  )
}

function CardDescription({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-description"
      className={cn("text-sm text-muted-foreground", className)}
      {...props}
    />
  )
}

function CardAction({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-action"
      className={cn(
        "col-start-2 row-span-2 row-start-1 self-start justify-self-end",
        className
      )}
      {...props}
    />
  )
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-content"
      className={cn("px-6 group-data-[size=sm]/card:px-4", className)}
      {...props}
    />
  )
}

function CardFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-footer"
      className={cn(
        "flex items-center rounded-b-xl px-6 group-data-[size=sm]/card:px-4 [.border-t]:pt-6 group-data-[size=sm]/card:[.border-t]:pt-4",
        className
      )}
      {...props}
    />
  )
}

export {
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardAction,
  CardDescription,
  CardContent,
}

// apps/tanstack-solid/src/components/card.tsx
import { cva } from "class-variance-authority";
import { cn } from "@niama/ui/lib/utils";
import type { JSX } from "solid-js";

const CARD = {
  base: cva(`group/card flex flex-col gap-6 overflow-hidden rounded-2xl bg-card py-6 text-card-foreground text-sm ring-1 ring-foreground/10 
    has-[>img:first-child]:pt-0 
    data-[size=sm]:gap-4 data-[size=sm]:py-4 
    *:[img:first-child]:rounded-t-xl *:[img:last-child]:rounded-b-xl`),
  header: cva(`group/card-header @container/card-header grid auto-rows-min items-start gap-2 rounded-t-xl px-6 
    has-data-[slot=card-action]:grid-cols-[1fr_auto] has-data-[slot=card-description]:grid-rows-[auto_auto] 
    group-data-[size=sm]/card:px-4 
    [.border-b]:pb-6 
    group-data-[size=sm]/card:[.border-b]:pb-4`),
  title: cva("font-heading font-medium text-base"),
  description: cva("text-muted-foreground text-sm"),
  content: cva(`px-6 
    group-data-[size=sm]/card:px-4`),
} as const;

export function Card(props: CardProps) {
  const { class: className, size = "default", ...rest } = props;
  return <div class={cn(CARD.base(), className)} data-size={size} data-slot="card" {...rest} />;
}

export function CardHeader(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const { class: className, ...rest } = props;
  return <div class={cn(CARD.header(), className)} data-slot="card-header" {...rest} />;
}

export function CardTitle(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const { class: className, ...rest } = props;
  return <div class={cn(CARD.title(), className)} data-slot="card-title" {...rest} />;
}

export function CardDescription(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const { class: className, ...rest } = props;
  return <div class={cn(CARD.description(), className)} data-slot="card-description" {...rest} />;
}

export function CardContent(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const { class: className, ...rest } = props;
  return <div class={cn(CARD.content(), className)} data-slot="card-content" {...rest} />;
}

export type CardProps = JSX.HTMLAttributes<HTMLDivElement> & {
  class?: string;
  "data-back"?: boolean;
  "data-discipline"?: string;
  "data-glow"?: boolean;
  size?: "default" | "sm";
};
