// packages/ui/src/components/react/section.tsx
import { cn } from "@niama/ui/lib/utils";
import { SECTION } from "@niama/ui/shared/section";
import { Separator } from "./separator";

// MAIN ------------------------------------------------------------------------------------------------------------------------------------
export function Section({ children, className, description, id, title, withSeparator }: SectionProps) {
  return (
    <section className={cn(SECTION.base(), className)} data-section id={id}>
      {withSeparator && <Separator className={SECTION.separator()} orientation="vertical" />}
      {title && <h2 className={SECTION.title()}>{title}</h2>}
      {description && <p className={SECTION.description()}>{description}</p>}
      {children}
    </section>
  );
}
export type SectionProps = React.ComponentProps<"section"> & { description?: string; id: string; title?: string; withSeparator?: boolean };

// apps/tanstack-solid/src/components/section.tsx
import { cn } from "@niama/ui/lib/utils";
import { SECTION } from "@niama/ui/shared/section";
import type { JSX } from "solid-js";
import { Separator } from "./separator";

export function Section(props: SectionProps) {
  const { children, class: className, description, id, title, withSeparator, ...rest } = props;

  return (
    <section class={cn(SECTION.base(), className)} data-section id={id} {...rest}>
      {withSeparator && <Separator class={SECTION.separator()} orientation="vertical" />}
      {title && <h2 class={SECTION.title()}>{title}</h2>}
      {description && <p class={SECTION.description()}>{description}</p>}
      {children}
    </section>
  );
}

export type SectionProps = {
  children?: JSX.Element;
  class?: string;
  description?: string;
  id: string;
  title?: string;
  withSeparator?: boolean;
};
