// packages/ui-react/src/components/ui/separator.tsx
import { Separator as SeparatorPrimitive } from "@base-ui/react/separator";
import { SEPARATOR } from "@niama/ui/separator";
import { cn } from "@niama/ui-react/lib/utils";

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function Separator({ className, orientation = "horizontal", ...props }: SeparatorProps) {
  return <SeparatorPrimitive className={cn(SEPARATOR.base(), className)} data-slot="separator" orientation={orientation} {...props} />;
}
export type SeparatorProps = Omit<SeparatorPrimitive.Props, "className"> & { className?: string };

// apps/tanstack-solid/src/components/separator.tsx
import { cn } from "@niama/ui/lib/utils";
import { SEPARATOR } from "@niama/ui/separator";
import type { JSX } from "solid-js";

export function Separator(props: SeparatorProps) {
  const { class: className, orientation = "horizontal", ...rest } = props;
  return (
    <div
      class={cn(SEPARATOR.base(), className)}
      data-horizontal={orientation === "horizontal" ? "" : undefined}
      data-orientation={orientation}
      data-slot="separator"
      data-vertical={orientation === "vertical" ? "" : undefined}
      {...rest}
    />
  );
}

export type SeparatorProps = JSX.HTMLAttributes<HTMLDivElement> & {
  class?: string;
  orientation?: "horizontal" | "vertical";
};
