// apps/tanstack-react/src/components/sky.tsx
import { cn } from "@niama/ui/lib/utils";
import { initializeSky, SKY, SKY_ORBITS } from "@niama/ui/shared/sky";
import { useEffect, useRef } from "react";

export type SkyProps = React.ComponentProps<"div">;

export function Sky({ className, ...props }: SkyProps) {
  const ref = useRef<HTMLDivElement | null>(null);

  useEffect(() => (ref.current ? initializeSky(ref.current) : undefined), []);

  return (
    <div className={cn(SKY.base(), className)}>
      <div className={SKY.orbits()}>
        {SKY_ORBITS.map((orbit) => (
          <div className={SKY.orbit()} key={orbit}>
            <div className={SKY.planet()} />
          </div>
        ))}
      </div>
      <div className={SKY.stars()} ref={ref} {...props}>
        <canvas className={SKY.canvas()} />
      </div>
    </div>
  );
}

// apps/tanstack-solid/src/components/sky.tsx
import { cn } from "@niama/ui/lib/utils";
import { initializeSky, SKY, SKY_ORBITS } from "@niama/ui/shared/sky";
import { onSettled } from "solid-js";

export function Sky(props: SkyProps) {
  const { class: className, ...rest } = props;
  let starsRef!: HTMLDivElement;

  onSettled(() => {
    if (starsRef) return initializeSky(starsRef);
  });

  return (
    <div class={cn(SKY.base(), className)}>
      <div class={SKY.orbits()}>
        {SKY_ORBITS.map((orbit) => (
          <div class={SKY.orbit()} data-orbit={orbit}>
            <div class={SKY.planet()} />
          </div>
        ))}
      </div>
      <div class={SKY.stars()} ref={starsRef} {...rest}>
        <canvas class={SKY.canvas()} />
      </div>
    </div>
  );
}

export type SkyProps = {
  class?: string;
};
