// packages/ui/src/components/react/theme-switcher.tsx
import { Button } from "@niama/ui/react/button";
import { themeStore, toggleThemeWithTransition } from "@niama/ui/shared/theme";
import { getThemeSwitcherLabel, THEME_SWITCHER } from "@niama/ui/shared/theme-switcher";
import { useSelector } from "@tanstack/react-store";
import { useRef } from "react";

// MAIN ------------------------------------------------------------------------------------------------------------------------------------
export function ThemeSwitcher() {
  const ref = useRef<HTMLButtonElement>(null);
  const theme = useSelector(themeStore);
  const label = getThemeSwitcherLabel(theme);

  const handleClick = () => toggleThemeWithTransition(ref.current);

  return (
    <Button
      aria-label={label}
      aria-pressed={theme === "dark"}
      className={THEME_SWITCHER.base()}
      onClick={handleClick}
      ref={ref}
      size="icon"
      suppressHydrationWarning
      title={label}
      type="button"
      variant="outline"
    >
      <span className={THEME_SWITCHER.sun()} />
      <span className={THEME_SWITCHER.moon()} />
      <span className="sr-only">{label}</span>
    </Button>
  );
}

// apps/tanstack-solid/src/components/theme-switcher.tsx
import { createSignal, createTrackedEffect } from "solid-js";
import { themeStore, toggleThemeWithTransition } from "@niama/ui/shared/theme";
import { THEME_SWITCHER, getThemeSwitcherLabel } from "@niama/ui/shared/theme-switcher";
import { Button } from "./button";

export function ThemeSwitcher() {
  const [theme, setTheme] = createSignal(themeStore.state);
  let buttonRef: HTMLButtonElement | undefined;

  createTrackedEffect(() => {
    if (typeof window === "undefined") return;

    const { unsubscribe } = themeStore.subscribe((value) => setTheme(value));
    return unsubscribe;
  });

  return (
    <Button
      ref={(el) => {
        buttonRef = el;
      }}
      aria-label={getThemeSwitcherLabel(theme())}
      aria-pressed={theme() === "dark" ? "true" : "false"}
      class={THEME_SWITCHER.base()}
      onClick={() => toggleThemeWithTransition(buttonRef ?? null)}
      size="icon"
      title={getThemeSwitcherLabel(theme())}
      variant="outline"
    >
      <span class={THEME_SWITCHER.sun()} />
      <span class={THEME_SWITCHER.moon()} />
      <span class="sr-only">{getThemeSwitcherLabel(theme())}</span>
    </Button>
  );
}
