// packages/ui-react/src/components/ui/loading-swap.tsx
import { LOADING_SWAP, type LoadingSwapStyles } from "@niama/ui/loading-swap";
import { cn } from "@niama/ui-react/lib/utils";

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function LoadingSwap({ isLoading, children, className }: LoadingSwapProps) {
  return (
    <div className={LOADING_SWAP.base()}>
      <div className={cn(LOADING_SWAP.children({ isLoading }), className)}>{children}</div>
      <div className={cn(LOADING_SWAP.loader({ isLoading }), className)}>
        <span className={LOADING_SWAP.spinner()} />
      </div>
    </div>
  );
}
export type LoadingSwapProps = React.PropsWithChildren & { className?: string } & LoadingSwapStyles;

// packages/ui-svelte/src/components/ui/loading-swap/loading-swap.svelte
<script lang="ts" module>
  import type { LoadingSwapStyles } from "@niama/ui/loading-swap";
  import type { HTMLAttributes } from "svelte/elements";

  export type LoadingSwapProps = Pick<HTMLAttributes<HTMLDivElement>, "children" | "class"> & LoadingSwapStyles;
</script>

<script lang="ts">
  import { LOADING_SWAP } from "@niama/ui/loading-swap";
  import { cn } from "@niama/ui-svelte/lib/utils";

  let { isLoading, children, class: className }: LoadingSwapProps = $props();
</script>

<div class={LOADING_SWAP.base()}>
  <div class={cn(LOADING_SWAP.children({ isLoading }), className)}>{@render children?.()}</div>
  <div class={cn(LOADING_SWAP.loader({ isLoading }), className)}>
    <span class={LOADING_SWAP.spinner()}></span>
  </div>
</div>
