// packages/ui-react/src/components/ui/label.tsx
import { cn } from "@niama/ui-react/lib/utils";
import { cva } from "class-variance-authority";

// STYLES ----------------------------------------------------------------------------------------------------------------------------------
export const LABEL = cva(`flex items-center gap-2 text-sm leading-none font-medium select-none 
	group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 
	peer-disabled:cursor-not-allowed peer-disabled:opacity-50`);

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function Label({ className, ...props }: React.ComponentProps<"label">) {
  // biome-ignore lint/a11y/noLabelWithoutControl: false positive
  return <label className={cn(LABEL(), className)} data-slot="label" {...props} />;
}

// packages/ui-svelte/src/components/label/label.svelte
<script lang="ts">
	import { Label as LabelPrimitive } from "bits-ui";
	import { cn } from "@niama/ui/lib/utils";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: LabelPrimitive.RootProps = $props();
</script>

<LabelPrimitive.Root
	bind:ref
	data-slot="label"
	class={cn(
		"gap-2 text-sm leading-none font-medium group-data-[disabled=true]:opacity-50 peer-disabled:opacity-50 flex items-center select-none group-data-[disabled=true]:pointer-events-none peer-disabled:cursor-not-allowed",
		className
	)}
	{...restProps}
/>
