// apps/sveltekit/src/lib/components/sky.svelte
<script lang="ts">
  import { cn } from "@niama/ui/lib/utils";
  import { initializeSky, SKY, SKY_ORBITS } from "@niama/ui/shared/sky";
  import { onMount } from "svelte";

  let { class: className = "" }: { class?: string } = $props();

  let container: HTMLDivElement | null = null;

  onMount(() => container && initializeSky(container));
</script>

<div aria-hidden="true" class={cn(SKY.base(), className)}>
  <div class={SKY.orbits()}>
    {#each SKY_ORBITS as orbit (orbit)}
      <div class={SKY.orbit()}><span class={SKY.planet()}></span></div>
    {/each}
  </div>
  <div bind:this={container} class={SKY.stars()}><canvas class={SKY.canvas()}></canvas></div>
</div>

// apps/tanstack-react/src/components/sky.tsx
import { cn } from "@niama/ui/lib/utils";
import { initializeSky, SKY, SKY_ORBITS } from "@niama/ui/shared/sky";
import { useEffect, useRef } from "react";

export type SkyProps = React.ComponentProps<"div">;

export function Sky({ className, ...props }: SkyProps) {
  const ref = useRef<HTMLDivElement | null>(null);

  useEffect(() => (ref.current ? initializeSky(ref.current) : undefined), []);

  return (
    <div className={cn(SKY.base(), className)}>
      <div className={SKY.orbits()}>
        {SKY_ORBITS.map((orbit) => (
          <div className={SKY.orbit()} key={orbit}>
            <div className={SKY.planet()} />
          </div>
        ))}
      </div>
      <div className={SKY.stars()} ref={ref} {...props}>
        <canvas className={SKY.canvas()} />
      </div>
    </div>
  );
}
