// apps/tanstack-solid/src/components/input.tsx
import { cva } from "class-variance-authority";
import { cn } from "@niama/ui/lib/utils";
import type { JSX } from "solid-js";

const INPUT = cva(`h-9 w-full min-w-0 rounded-4xl border border-input bg-input/30 px-3 py-1 text-base outline-none transition-colors 
	file:inline-flex file:h-7 file:border-0 file:bg-transparent file:font-medium file:text-foreground file:text-sm 
	placeholder:text-muted-foreground 
	focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 
	disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 
	aria-invalid:border-destructive aria-invalid:ring-[3px] aria-invalid:ring-destructive/20 
	md:text-sm 
	dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40`);

export function Input(props: InputProps) {
  const { class: className, ...rest } = props;
  return <input class={cn(INPUT(), className)} data-slot="input" {...rest} />;
}

export type InputProps = JSX.InputHTMLAttributes<HTMLInputElement> & {
  class?: string;
};

// packages/ui-react/src/components/input.tsx
import { Input as InputPrimitive } from "@base-ui/react/input";
import { cva } from "class-variance-authority";
import { cn } from "@niama/ui/lib/utils";

// STYLES ----------------------------------------------------------------------------------------------------------------------------------
export const INPUT = cva(`h-9 w-full min-w-0 rounded-4xl border border-input bg-input/30 px-3 py-1 text-base outline-none transition-colors 
	file:inline-flex file:h-7 file:border-0 file:bg-transparent file:font-medium file:text-foreground file:text-sm 
	placeholder:text-muted-foreground 
	focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 
	disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 
	aria-invalid:border-destructive aria-invalid:ring-[3px] aria-invalid:ring-destructive/20 
	md:text-sm 
	dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40`);

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function Input({ className, type, ...props }: InputProps) {
  return <InputPrimitive className={cn(INPUT(), className)} data-slot="input" type={type} {...props} />;
}
export type InputProps = React.ComponentProps<"input">;
