// packages/ui-svelte/src/components/ui/separator/separator.svelte
<script lang="ts">
  import { cn } from "@niama/ui-svelte/lib/utils";
  import { Separator as SeparatorPrimitive } from "bits-ui";

  let {
    ref = $bindable(null),
    class: className,
    "data-slot": dataSlot = "separator",
    ...restProps
  }: SeparatorPrimitive.RootProps = $props();
</script>

<SeparatorPrimitive.Root
  bind:ref
  data-slot={dataSlot}
  class={cn(
		"bg-border shrink-0 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:w-px",
		// this is different in shadcn/ui but self-stretch breaks things for us
		"data-[orientation=vertical]:h-full",
		className
	)}
  {...restProps}
/>

// packages/ui-react/src/components/separator.tsx
import { Separator as SeparatorPrimitive } from "@base-ui/react/separator";
import { cva } from "class-variance-authority";
import { cn } from "@niama/ui/lib/utils";

// STYLES ----------------------------------------------------------------------------------------------------------------------------------
export const SEPARATOR = cva(`shrink-0 bg-border 
	data-horizontal:h-px data-horizontal:w-full 
	data-vertical:w-px data-vertical:self-stretch`);

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function Separator({ className, orientation = "horizontal", ...props }: SeparatorProps) {
  return <SeparatorPrimitive className={cn(SEPARATOR(), className)} data-slot="separator" orientation={orientation} {...props} />;
}
export type SeparatorProps = Omit<SeparatorPrimitive.Props, "className"> & { className?: string };
