// apps/tanstack-solid/src/components/disciplines/carousel.tsx
import type { Disciplines } from "@niama/domain/functions/disciplines";
import { cn } from "@niama/ui/lib/utils";
import { DISCIPLINE, DISCIPLINES, AUTOPLAY } from "@niama/ui/shared/disciplines/carousel";
import { bindGlows } from "@niama/ui/shared/glow";
import { prefersReducedMotion } from "@niama/ui/shared/motion";
import { createTrackedEffect } from "solid-js";
import { Card, CardContent } from "../card";
import { Logo } from "../logo";

export function DisciplinesCarousel(props: DisciplinesCarouselProps) {
  const { items } = props;
  let viewportRef: HTMLDivElement | undefined;

  const scrollNext = () => {
    if (!viewportRef) return;
    viewportRef.scrollBy({ left: viewportRef.clientWidth * 0.88, behavior: "smooth" });
  };

  const scrollPrev = () => {
    if (!viewportRef) return;
    viewportRef.scrollBy({ left: -viewportRef.clientWidth * 0.88, behavior: "smooth" });
  };

  createTrackedEffect(() => {
    if (typeof window === "undefined") return;

    const cleanupGlow = bindGlows();
    let timer: number | undefined;

    if (!prefersReducedMotion()) {
      timer = window.setInterval(scrollNext, AUTOPLAY);
    }

    return () => {
      if (timer) window.clearInterval(timer);
      for (const cleanup of cleanupGlow) cleanup();
    };
  });

  return (
    <section class={DISCIPLINES.base()}>
      <div class={DISCIPLINES.carousel()}>
        <div
          ref={viewportRef}
          class="overflow-x-clip overflow-y-visible py-6 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
          style={{ "scroll-snap-type": "x mandatory" }}
        >
          <div class="flex w-max">
            {items.map((item) => (
              <div class={DISCIPLINES.item()} style={{ "scroll-snap-align": "center" }}>
                <DisciplineItem item={item} />
              </div>
            ))}
          </div>
        </div>
        <aside class={DISCIPLINES.controls()}>
          <button aria-label="Voie précédente" class={DISCIPLINES.control()} onClick={scrollPrev} type="button">
            <span class="icon-[tabler--chevron-left]" />
          </button>
          <button aria-label="Voie suivante" class={DISCIPLINES.control()} onClick={scrollNext} type="button">
            <span class="icon-[tabler--chevron-right]" />
          </button>
        </aside>
      </div>
    </section>
  );
}

export type DisciplinesCarouselProps = { items: Disciplines["Entity"][] };

function DisciplineItem(props: DisciplineItemProps) {
  const { class: className, item, ...rest } = props;

  return (
    <Card class={cn(DISCIPLINE.base(), className)} data-discipline={item.slug} data-glow {...rest}>
      <CardContent class={DISCIPLINE.media()}>
        <Logo class={DISCIPLINE.logo()} discipline={item} />
      </CardContent>
      <CardContent class={DISCIPLINE.content()}>
        <h3 class={DISCIPLINE.title()}>{item.title}</h3>
        {item.description.map((sentence) => (
          <p class={DISCIPLINE.description()}>{sentence}</p>
        ))}
      </CardContent>
    </Card>
  );
}

type DisciplineItemProps = {
  class?: string;
  item: Disciplines["Entity"];
};

// apps/tanstack/src/components/disciplines/carousel.tsx
import type { Disciplines } from "@niama/domain/functions/disciplines";
import { cn } from "@niama/ui/lib/utils";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@niama/ui/react/carousel";
import { Item, ItemContent, ItemDescription, ItemMedia, type ItemProps, ItemTitle } from "@niama/ui/react/item";
import { Logo } from "@niama/ui/react/logo";
import { AUTOPLAY, DISCIPLINE, DISCIPLINES } from "@niama/ui/shared/disciplines/carousel";
import { GLOW } from "@niama/ui/shared/glow";
import Autoplay from "embla-carousel-autoplay";
import Ssr from "embla-carousel-ssr";
import { useGlow } from "../use-glow";

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function DisciplinesCarousel({ items }: DisciplinesCarouselProps) {
  return (
    <section className={DISCIPLINES.base()}>
      <Carousel className={DISCIPLINES.carousel()} opts={{ loop: true }} plugins={[Autoplay({ delay: AUTOPLAY }), Ssr()]}>
        <CarouselContent>
          {items.map((item) => (
            <CarouselItem className={DISCIPLINES.item()} key={item.slug}>
              <DisciplineItem item={item} />
            </CarouselItem>
          ))}
        </CarouselContent>
        <aside className={DISCIPLINES.controls()}>
          <CarouselPrevious className={DISCIPLINES.control()} />
          <CarouselNext className={DISCIPLINES.control()} />
        </aside>
      </Carousel>
    </section>
  );
}
export type DisciplinesCarouselProps = { items: Disciplines["Entity"][] };

// ITEM ------------------------------------------------------------------------------------------------------------------------------------
function DisciplineItem({ className, item, ...r }: DisciplineItemProps) {
  const { props, ref } = useGlow();

  return (
    <Item className={cn(DISCIPLINE.base(), GLOW(), className)} data-discipline={item.slug} ref={ref} variant="outline" {...r} {...props}>
      <ItemMedia className={DISCIPLINE.media()}>
        <Logo className={DISCIPLINE.logo()} discipline={item} />
      </ItemMedia>
      <ItemContent className={DISCIPLINE.content()}>
        <ItemTitle className={DISCIPLINE.title()}>{item.title}</ItemTitle>
        {item.description.map((sentence) => (
          <ItemDescription className={DISCIPLINE.description()} key={sentence}>
            {sentence}
          </ItemDescription>
        ))}
      </ItemContent>
    </Item>
  );
}
type DisciplineItemProps = ItemProps & { item: Disciplines["Entity"] };
