// packages/ui-solid/src/components/disciplines/carousel.tsx
import type { Disciplines } from "@niama/domain/functions/disciplines";
import { createCarouselStore } from "@niama/ui/carousel";
import { AUTOPLAY, DISCIPLINE, DISCIPLINES } from "@niama/ui/disciplines/carousel";
import { GLOW } from "@niama/ui/glow";
import { cn } from "@niama/ui-solid/lib/utils";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@niama/ui-solid/ui/carousel";
import { Item, ItemContent, ItemDescription, ItemMedia, ItemTitle } from "@niama/ui-solid/ui/item";
import { Logo } from "@niama/ui-solid/ui/logo";
import Autoplay from "embla-carousel-autoplay";
import Ssr from "embla-carousel-ssr";
import { For, splitProps } from "solid-js";

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function DisciplinesCarousel(props: DisciplinesCarouselProps) {
  const store = createCarouselStore({ loop: true }, [Autoplay({ delay: AUTOPLAY }), Ssr()]);

  return (
    <section class={DISCIPLINES.base()}>
      <Carousel class={DISCIPLINES.carousel()} store={store}>
        <CarouselContent>
          <For each={props.items}>
            {(item) => (
              <CarouselItem class={DISCIPLINES.item()}>
                <DisciplineItem item={item} />
              </CarouselItem>
            )}
          </For>
        </CarouselContent>
        <aside class={DISCIPLINES.controls()}>
          <CarouselPrevious class={DISCIPLINES.control()} />
          <CarouselNext class={DISCIPLINES.control()} />
        </aside>
      </Carousel>
    </section>
  );
}
export type DisciplinesCarouselProps = { items: Disciplines["Entity"][] };

// ITEM ------------------------------------------------------------------------------------------------------------------------------------
function DisciplineItem(props: DisciplineItemProps) {
  const [local, others] = splitProps(props, ["class", "item"]);

  return (
    <Item class={cn(DISCIPLINE.base(), GLOW(), local.class)} data-discipline={local.item.slug} variant="outline" {...others}>
      <ItemMedia class={DISCIPLINE.media()}>
        <Logo class={DISCIPLINE.logo()} discipline={local.item} />
      </ItemMedia>
      <ItemContent class={DISCIPLINE.content()}>
        <ItemTitle class={DISCIPLINE.title()}>{local.item.title}</ItemTitle>
        <For each={local.item.description}>
          {(sentence) => <ItemDescription class={DISCIPLINE.description()}>{sentence}</ItemDescription>}
        </For>
      </ItemContent>
    </Item>
  );
}
type DisciplineItemProps = { class?: string; item: Disciplines["Entity"] };

// apps/tanstack/src/components/disciplines/carousel.tsx
import type { Disciplines } from "@niama/domain/functions/disciplines";
import { cn } from "@niama/ui/lib/utils";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@niama/ui/react/carousel";
import { Item, ItemContent, ItemDescription, ItemMedia, type ItemProps, ItemTitle } from "@niama/ui/react/item";
import { Logo } from "@niama/ui/react/logo";
import { createCarouselStore } from "@niama/ui/shared/carousel";
import { AUTOPLAY, DISCIPLINE, DISCIPLINES } from "@niama/ui/shared/disciplines/carousel";
import { GLOW } from "@niama/ui/shared/glow";
import Autoplay from "embla-carousel-autoplay";
import Ssr from "embla-carousel-ssr";
import { useState } from "react";
import { useGlow } from "../use-glow";

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function DisciplinesCarousel({ items }: DisciplinesCarouselProps) {
  const [store] = useState(() => createCarouselStore({ loop: true }, [Autoplay({ delay: AUTOPLAY }), Ssr()]));

  return (
    <section className={DISCIPLINES.base()}>
      <Carousel className={DISCIPLINES.carousel()} store={store}>
        <CarouselContent>
          {items.map((item) => (
            <CarouselItem className={DISCIPLINES.item()} key={item.slug}>
              <DisciplineItem item={item} />
            </CarouselItem>
          ))}
        </CarouselContent>
        <aside className={DISCIPLINES.controls()}>
          <CarouselPrevious className={DISCIPLINES.control()} />
          <CarouselNext className={DISCIPLINES.control()} />
        </aside>
      </Carousel>
    </section>
  );
}
export type DisciplinesCarouselProps = { items: Disciplines["Entity"][] };

// ITEM ------------------------------------------------------------------------------------------------------------------------------------
function DisciplineItem({ className, item, ...r }: DisciplineItemProps) {
  const { props, ref } = useGlow();

  return (
    <Item className={cn(DISCIPLINE.base(), GLOW(), className)} data-discipline={item.slug} ref={ref} variant="outline" {...r} {...props}>
      <ItemMedia className={DISCIPLINE.media()}>
        <Logo className={DISCIPLINE.logo()} discipline={item} />
      </ItemMedia>
      <ItemContent className={DISCIPLINE.content()}>
        <ItemTitle className={DISCIPLINE.title()}>{item.title}</ItemTitle>
        {item.description.map((sentence) => (
          <ItemDescription className={DISCIPLINE.description()} key={sentence}>
            {sentence}
          </ItemDescription>
        ))}
      </ItemContent>
    </Item>
  );
}
type DisciplineItemProps = ItemProps & { item: Disciplines["Entity"] };
