// packages/ui/src/components/react/carousel.tsx
import { createStoreContext, useSelector } from "@tanstack/react-store";
import type { EmblaOptionsType, EmblaPluginType } from "embla-carousel";
import useEmblaCarousel, { type EmblaRootNodeRefType } from "embla-carousel-react";
import { useEffect, useState } from "react";
import { cn } from "../../lib/utils";
import { CAROUSEL, createCarouselStore } from "../shared/carousel";
import { Button } from "./button";

// CONTEXT ---------------------------------------------------------------------------------------------------------------------------------
const { StoreProvider: CarouselProvider, useStoreContext: useCarousel } = createStoreContext<CarouselContextProps>();
type CarouselContextProps = { ref: EmblaRootNodeRefType; store: ReturnType<typeof createCarouselStore> };

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function Carousel({ opts: inputOpts = {}, plugins, className, children, ...rest }: CarouselProps) {
  const [store] = useState(() => createCarouselStore(inputOpts));
  const opts = useSelector(store, (state) => state.opts);
  const [ref, api] = useEmblaCarousel(opts, plugins);

  useEffect(() => (api ? store.actions.bindApi(api) : undefined), [api, store]);

  return (
    <CarouselProvider value={{ ref, store }}>
      <section
        aria-roledescription="carousel"
        className={cn(CAROUSEL.base(), className)}
        data-axis={opts.axis ?? "x"}
        data-slot="carousel"
        onKeyDownCapture={store.actions.handleKeydown}
        role="region"
        {...rest}
      >
        {children}
      </section>
    </CarouselProvider>
  );
}
export type CarouselProps = React.ComponentProps<"section"> & { opts?: EmblaOptionsType; plugins?: EmblaPluginType[] };

// CONTENT ---------------------------------------------------------------------------------------------------------------------------------
export function CarouselContent({ className, viewportClassName, ...props }: CarouselContentProps) {
  const { ref } = useCarousel();

  return (
    <div className={cn(CAROUSEL.viewport(), viewportClassName)} data-slot="carousel-content" ref={ref}>
      <div className={cn(CAROUSEL.content(), className)} {...props} />
    </div>
  );
}
export type CarouselContentProps = React.ComponentProps<"div"> & { viewportClassName?: string };

// ITEM ------------------------------------------------------------------------------------------------------------------------------------
export function CarouselItem({ className, ...props }: CarouselItemProps) {
  return <section className={cn(CAROUSEL.item(), className)} data-slot="carousel-item" {...props} />;
}
export type CarouselItemProps = React.ComponentProps<"section">;

// NEXT ------------------------------------------------------------------------------------------------------------------------------------
export function CarouselNext({ className, variant = "outline", size = "icon-sm", ...props }: CarouselNextProps) {
  const { store } = useCarousel();
  const { api, canGoToNext } = useSelector(store, (state) => state);

  return (
    <Button
      className={cn(CAROUSEL.next(), className)}
      data-slot="carousel-next"
      disabled={!canGoToNext}
      onClick={() => api?.goToNext()}
      size={size}
      variant={variant}
      {...props}
    >
      <span className="icon-[tabler--chevron-right]" />
      <span className="sr-only">Suivant</span>
    </Button>
  );
}
export type CarouselNextProps = Omit<React.ComponentProps<typeof Button>, "className"> & { className?: string };

// PREVIOUS --------------------------------------------------------------------------------------------------------------------------------
export function CarouselPrevious({ className, variant = "outline", size = "icon-sm", ...props }: CarouselPreviousProps) {
  const { store } = useCarousel();
  const { api, canGoToPrev } = useSelector(store, (state) => state);

  return (
    <Button
      className={cn(CAROUSEL.previous(), className)}
      data-slot="carousel-previous"
      disabled={!canGoToPrev}
      onClick={() => api?.goToPrev()}
      size={size}
      variant={variant}
      {...props}
    >
      <span className="icon-[tabler--chevron-left]" />
      <span className="sr-only">Précédent</span>
    </Button>
  );
}
export type CarouselPreviousProps = Omit<React.ComponentProps<typeof Button>, "className"> & { className?: string };

// packages/ui/src/components/svelte/carousel/carousel.svelte
<script lang="ts">
  import { cn, type WithElementRef } from "@niama/ui/lib/utils";
  import { CAROUSEL, createCarouselStore } from "@niama/ui/shared/carousel";
  import { useSelector as readStore } from "@tanstack/svelte-store";
  import { type CarouselProps, setEmblaContext } from "./context";

  let {
    ref = $bindable(null),
    store,
    opts = {},
    plugins = [],
    class: className,
    children,
    ...restProps
  }: WithElementRef<CarouselProps> = $props();

  const carouselStore = store ?? createCarouselStore(opts, plugins);
  const carouselOpts = readStore(carouselStore, (state) => state.opts);

  setEmblaContext({ store: carouselStore });

  $effect(() => {
    if (store) return;
    carouselStore.setState((prev) => ({ ...prev, opts, plugins }));
    carouselStore.state.api?.reInit(opts, plugins);
  });
</script>

<section
  bind:this={ref}
  aria-roledescription="carousel"
  class={cn(CAROUSEL.base(), className)}
  data-axis={carouselOpts.current.axis ?? "x"}
  data-slot="carousel"
  onkeydowncapture={carouselStore.actions.handleKeydown}
  role="region"
  {...restProps}
>
  {@render children?.()}
</section>
