// packages/ui-solid/src/components/ui/loading-swap.tsx
import { LOADING_SWAP, type LoadingSwapStyles } from "@niama/ui/loading-swap";
import { cn } from "@niama/ui-solid/lib/utils";
import { type ComponentProps, splitProps } from "solid-js";

// MAIN ------------------------------------------------------------------------------------------------------------------------------------
export function LoadingSwap(props: LoadingSwapProps) {
  const [local, others] = splitProps(props, ["children", "class", "isLoading"]);
  return (
    <div class={LOADING_SWAP.base()} {...others}>
      <div class={cn(LOADING_SWAP.children({ isLoading: local.isLoading }), local.class)}>{local.children}</div>
      <div class={cn(LOADING_SWAP.loader({ isLoading: local.isLoading }), local.class)}>
        <span class={LOADING_SWAP.spinner()} />
      </div>
    </div>
  );
}
export type LoadingSwapProps = ComponentProps<"div"> & LoadingSwapStyles;

// packages/ui-react/src/components/ui/loading-swap.tsx
import { LOADING_SWAP, type LoadingSwapStyles } from "@niama/ui/loading-swap";
import { cn } from "@niama/ui-react/lib/utils";

// BASE ------------------------------------------------------------------------------------------------------------------------------------
export function LoadingSwap({ isLoading, children, className }: LoadingSwapProps) {
  return (
    <div className={LOADING_SWAP.base()}>
      <div className={cn(LOADING_SWAP.children({ isLoading }), className)}>{children}</div>
      <div className={cn(LOADING_SWAP.loader({ isLoading }), className)}>
        <span className={LOADING_SWAP.spinner()} />
      </div>
    </div>
  );
}
export type LoadingSwapProps = React.PropsWithChildren & { className?: string } & LoadingSwapStyles;
