// apps/sveltekit/src/lib/components/the-header.svelte
<script lang="ts">
  import type { ReadPublicLayoutProps } from "@niama/domain/functions/layouts";
  import { headerStore, selectStainStyle } from "@niama/ui/lib/stores/header";
  import { clearHovered, observeNavLink, THE_HEADER } from "@niama/ui/shared/the-header";
  import { Button } from "@niama/ui/svelte/button";
  import { Logo } from "@niama/ui/svelte/logo";
  import { Section } from "@niama/ui/svelte/section";
  import { Separator } from "@niama/ui/svelte/separator";
  import { ThemeSwitcher } from "@niama/ui/svelte/theme-switcher";
  import { useStore as readStore } from "@tanstack/svelte-store";
  import { onMount } from "svelte";

  let { navs }: Pick<ReadPublicLayoutProps, "navs"> = $props();

  let currentHash = $state("");
  let isMenuOpen = $state(false);

  const stainStyle = readStore(headerStore, selectStainStyle);

  const hoverNav = (hash: string) => {
    headerStore.actions.setHovered(hash);
  };

  const styleFromBounds = (style?: Partial<CSSStyleDeclaration>) =>
    style ? `height:${style.height};opacity:${style.opacity};transform:${style.transform};width:${style.width};` : "opacity:0;";

  const stainInlineStyle = $derived(styleFromBounds(stainStyle.current));

  const syncHash = () => {
    const hash = window.location.hash.replace("#", "");
    currentHash = hash === "top" ? "" : hash;
    headerStore.actions.setActive(currentHash || undefined);
    isMenuOpen = false;
  };

  onMount(() => {
    const links = Array.from(document.querySelectorAll<HTMLElement>("[data-nav-link]"));
    const cleaners = links.flatMap((link) => {
      const hash = link.dataset.navLink;
      return hash ? [observeNavLink(hash, link)] : [];
    });

    syncHash();
    window.addEventListener("hashchange", syncHash);

    return () => {
      window.removeEventListener("hashchange", syncHash);
      for (const clean of cleaners) clean();
    };
  });
</script>

<div class={THE_HEADER.wrapper()}>
  <header class={THE_HEADER.base()}>
    <a aria-label="Retour à l'accueil" class={THE_HEADER.logo()} href="/#top"> <Logo showTitle={false} /> </a>

    <div class={THE_HEADER.actions()}>
      <ThemeSwitcher />
      <Button
        aria-expanded={isMenuOpen}
        aria-label="Menu"
        class={THE_HEADER.burger()}
        onclick={() => {
					isMenuOpen = !isMenuOpen;
				}}
        size="icon"
        variant="outline"
      >
        <span class={THE_HEADER.burgerIcon()}></span>
      </Button>
    </div>
  </header>

  {#if isMenuOpen}
    <nav class={`${THE_HEADER.burgerContent()} absolute top-full right-0 mt-2 flex flex-col gap-2 sm:hidden`}>
      {#each navs as nav (nav.key)}
        <Button class={THE_HEADER.burgerItem()} href={`${nav.to}#${nav.hash}`} onclick={() => (isMenuOpen = false)} variant="ghost">
          {nav.text}
        </Button>
      {/each}
    </nav>
  {/if}
</div>

<Section class="flex justify-center" id="top-1">
  <a aria-label="Retour à l'accueil" class={THE_HEADER.logoMain()} href="/#top"> <Logo class="w-full" /> </a>
</Section>
<Separator class="self-center! h-6" orientation="vertical" />
<Section class={THE_HEADER.menu()} id="top-2">
  <nav class={THE_HEADER.nav()} onmouseleave={clearHovered}>
    <div aria-hidden="true" class={THE_HEADER.stain()} data-nav-stain style={stainInlineStyle}></div>
    {#each navs as nav (nav.key)}
      <Button
        aria-current={currentHash === nav.hash ? "page" : undefined}
        class={THE_HEADER.navLink()}
        data-nav-link={nav.hash}
        href={`${nav.to}#${nav.hash}`}
        onclick={() => {
					isMenuOpen = false;
				}}
        onmouseenter={() => hoverNav(nav.hash)}
        variant="ghost"
      >
        <span class={THE_HEADER.stainContent()}>{nav.text}</span>
      </Button>
    {/each}
  </nav>
</Section>
<Separator class="self-center! h-24" orientation="vertical" />

// apps/tanstack/src/routes/_public/-the-header.tsx
import { headerStore, selectStainStyle, setActive, setHovered } from "@niama/ui/lib/stores/header";
import { Button } from "@niama/ui/react/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuTrigger } from "@niama/ui/react/dropdown-menu";
import { Logo } from "@niama/ui/react/logo";
import { Separator } from "@niama/ui/react/separator";
import { clearHovered, observeNavLink, THE_HEADER } from "@niama/ui/shared/the-header";
import { Link, useLocation } from "@tanstack/react-router";
import { useStore } from "@tanstack/react-store";
import { useEffect, useRef } from "react";
import { Section } from "@/components/section";
import type { ReadPublicLayoutProps } from "@/lib/layouts";
import { HeaderThemeSwitcher } from "./-the-header.theme-switcher";

// MAIN ------------------------------------------------------------------------------------------------------------------------------------
export function TheHeader({ navs }: Pick<ReadPublicLayoutProps, "navs">) {
	const hash = useLocation({ select: ({ hash }) => hash });
	const stainStyle = useStore(headerStore, selectStainStyle);

	useEffect(() => setActive(navs.find((nav) => nav.hash === hash)?.hash), [hash, navs]);

	return (
		<>
			<div className={THE_HEADER.wrapper()}>
				<header className={THE_HEADER.base()}>
					<Link aria-label="Retour à l'accueil" className={THE_HEADER.logo()} to="/">
						<Logo showTitle={false} />
					</Link>

					<div className={THE_HEADER.actions()}>
						<HeaderThemeSwitcher />
						{/* <HeaderUser signInUrl={signInUrl} signUpUrl={signUpUrl} /> */}
						<HeaderBurger navs={navs} />
					</div>
				</header>
			</div>
			<Section className="flex justify-center" id="top-1">
				<Link aria-label="Retour à l'accueil" className={THE_HEADER.logoMain()} to="/">
					<Logo className="w-full" />
				</Link>
			</Section>
			<Separator className="self-center! h-6" orientation="vertical" />
			<Section className={THE_HEADER.menu()} id="top-2">
				<nav className={THE_HEADER.nav()} onMouseLeave={clearHovered}>
					<div aria-hidden="true" className={THE_HEADER.stain()} style={stainStyle}></div>
					{navs.map((nav) => (
						<Link {...nav} activeOptions={{ includeHash: true }} key={nav.key} resetScroll={false}>
							<HeaderNav nav={nav} />
						</Link>
					))}
				</nav>
			</Section>
			<Separator className="self-center! h-24" orientation="vertical" />
		</>
	);
}

// NAV -------------------------------------------------------------------------------------------------------------------------------------
function HeaderNav({ nav: { hash, text } }: HeaderNavProps) {
	const ref = useRef<HTMLButtonElement | null>(null);

	const handleOnMouseEnter = () => setHovered(hash);

	useEffect(() => (ref.current ? observeNavLink(hash, ref.current) : undefined), [hash]);

	return (
		<button ref={ref} className={THE_HEADER.navLink()} type="button" onMouseEnter={handleOnMouseEnter}>
			<span className={THE_HEADER.stainContent()}>{text}</span>
		</button>
	);
}
export type HeaderNavProps = { nav: ReadPublicLayoutProps["navs"][number] };

// BURGER ----------------------------------------------------------------------------------------------------------------------------------
function HeaderBurger({ navs }: Pick<ReadPublicLayoutProps, "navs">) {
	return (
		<DropdownMenu>
			<DropdownMenuTrigger
				render={
					<Button aria-label="Menu" className={THE_HEADER.burger()} size="icon" variant="outline">
						<span className={THE_HEADER.burgerIcon()} />
					</Button>
				}
			/>
			<DropdownMenuContent align="end" className={THE_HEADER.burgerContent()} sideOffset={18}>
				<DropdownMenuGroup>
					{navs.map(({ key, ...nav }) => (
						<DropdownMenuItem
							className={THE_HEADER.burgerItem()}
							key={key}
							render={<Link {...nav} activeOptions={{ includeHash: true }} resetScroll={false} />}
						>
							{nav.text}
						</DropdownMenuItem>
					))}
				</DropdownMenuGroup>
			</DropdownMenuContent>
		</DropdownMenu>
	);
}

// USER ------------------------------------------------------------------------------------------------------------------------------------
// function HeaderUser({ signInUrl, signUpUrl }: { signInUrl: string; signUpUrl: string }) {
//   const { signOut, user } = useAuth();

//   if (!user)
//     return (
//       <DropdownMenu>
//         <DropdownMenuTrigger
//           render={
//             <Button size="icon">
//               <span className="icon-[tabler--user]" />
//             </Button>
//           }
//         />
//         <DropdownMenuContent align="end" className="w-(--radix-dropdown-menu-trigger-width) min-w-56 rounded-lg" sideOffset={4}>
//           <DropdownMenuGroup>
//             <DropdownMenuItem render={<a href={signInUrl} />}>
//               <span className="icon-[tabler--login]" />
//               Je me connecte
//             </DropdownMenuItem>
//             <DropdownMenuItem render={<a href={signUpUrl} />}>
//               <span className="icon-[tabler--user-plus]" />
//               Je m'inscris
//             </DropdownMenuItem>
//           </DropdownMenuGroup>
//         </DropdownMenuContent>
//       </DropdownMenu>
//     );

//   return (
//     <DropdownMenu>
//       <DropdownMenuTrigger
//         render={
//           <Button size="icon">
//             <span className="icon-[tabler--user]" />
//           </Button>
//         }
//       />
//       <DropdownMenuContent align="end" className="w-(--radix-dropdown-menu-trigger-width) min-w-56 rounded-lg" side="right" sideOffset={4}>
//         <DropdownMenuGroup>
//           <DropdownMenuLabel className="p-0 font-normal">
//             <div className="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
//               <Avatar className="h-8 w-8 rounded-lg">
//                 <AvatarImage alt={user?.name} src={user?.avatar} />
//                 <AvatarFallback className="rounded-lg">CN</AvatarFallback>
//               </Avatar>
//               <div className="grid flex-1 text-left text-sm leading-tight">
//                 <span className="truncate font-medium">{user?.name}</span>
//                 <span className="truncate text-muted-foreground text-xs">{user?.email}</span>
//               </div>
//             </div>
//           </DropdownMenuLabel>
//         </DropdownMenuGroup>
//         <DropdownMenuSeparator />
//         <DropdownMenuGroup>
//           <DropdownMenuItem>
//             <span className="icon-[tabler--user-circle]" />
//             Mon compte
//           </DropdownMenuItem>
//           <DropdownMenuItem>
//             <span className="icon-[tabler--notification]" />
//             Mes notifications
//           </DropdownMenuItem>
//         </DropdownMenuGroup>
//         <DropdownMenuSeparator />
//         <DropdownMenuItem onClick={() => signOut()}>
//           <span className="icon-[tabler--logout]" />
//           Je me déconnecte
//         </DropdownMenuItem>
//       </DropdownMenuContent>
//     </DropdownMenu>
//   );
// }
