// packages/ui-svelte/src/components/form/field/field.svelte
<script lang="ts" module>
  import type { Snippet } from "svelte";
  export type FieldProps = { children: Snippet<[boolean]>; label: string };
</script>

<script lang="ts">
  import { FIELD } from "@niama/ui/form/field";
  import { useFieldContext } from "@niama/ui-svelte/hooks/form-context";
  import { FieldLabel, Field as FieldNative } from "@niama/ui-svelte/ui/field";
  import FieldError from "./field-error.svelte";

  let { children, label }: FieldProps = $props();

  const { form, name, state } = useFieldContext<string>();
  const isInvalid = $derived((form.state.submissionAttempts > 0 || state.meta.isBlurred) && !state.meta.isValid);
</script>

<FieldNative class={FIELD.field()} data-invalid={isInvalid}>
  <FieldLabel class={FIELD.label()} for={name}> {label} </FieldLabel>
  {@render children?.(isInvalid)}
  <FieldError errors={state.meta.errors} {isInvalid} />
</FieldNative>

// packages/ui-react/src/components/form/field.tsx
import { useFieldContext } from "@niama/ui-react/hooks/form-context";
import { FieldError as FieldErrorNative, FieldLabel, Field as FieldNative } from "@niama/ui-react/field";
import { cva } from "class-variance-authority";
import { useMemo } from "react";

// STYLES ----------------------------------------------------------------------------------------------------------------------------------
const FIELD = {
	error: cva(
		`flex origin-top items-center gap-2 overflow-hidden rounded-full font-normal bg-destructive px-2 text-destructive-foreground 
    transition-[max-height] duration-150 ease-in`,
		{ variants: { isInvalid: { true: "max-h-10", false: "max-h-0" } } },
	),
	errorIcon: cva("icon-[lucide--circle-alert] size-4 py-8"),
	field: cva("gap-2"),
	label: cva(""),
};

// FIELD -----------------------------------------------------------------------------------------------------------------------------------
export function Field({ children, label }: FieldProps) {
	const { form, name, state } = useFieldContext<string>();
	const isInvalid = useMemo(
		() => (form.state.submissionAttempts > 0 || state.meta.isBlurred) && !state.meta.isValid,
		[form.state.submissionAttempts, state.meta.isBlurred, state.meta.isValid],
	);

	return (
		<FieldNative className={FIELD.field()} data-invalid={isInvalid}>
			<FieldLabel className={FIELD.label()} htmlFor={name}>
				{label}
			</FieldLabel>
			{children(isInvalid)}
			<FieldError errors={state.meta.errors} isInvalid={isInvalid} />
		</FieldNative>
	);
}
export type FieldProps = { children: (isInvalid: boolean) => React.ReactNode; label: string };

// ERROR -----------------------------------------------------------------------------------------------------------------------------------
export function FieldError({ errors, isInvalid }: FieldErrorProps) {
	return (
		<FieldErrorNative className={FIELD.error({ isInvalid })} errors={errors}>
			<span className={FIELD.errorIcon()} />
			{errors[0]?.message}
		</FieldErrorNative>
	);
}
export type FieldErrorProps = {
	errors: { message?: string }[];
	isInvalid: boolean;
};
