// packages/ui-svelte/src/components/form/textarea-field/textarea-field.svelte
<script lang="ts" module>
	export type TextareaFieldProps = { label: string };
</script>

<script lang="ts">
  import { Field } from "@niama/ui-svelte/form/field";
  import { useFieldContext } from "@niama/ui-svelte/hooks/form-context";
  import { Textarea } from "@niama/ui-svelte/ui/textarea";

  let { handleBlur, handleChange, name, state } = useFieldContext<string>();
  let { label } = $props();
</script>

<Field {label}>
  {#snippet children(isInvalid)}
    <Textarea
      aria-invalid={isInvalid}
      id={name}
      onblur={handleBlur}
      onchange={(e) => handleChange((e.target as HTMLTextAreaElement).value)}
      placeholder={label}
      value={state.value}
    />
  {/snippet}
</Field>

// packages/ui-react/src/components/form/textarea-field.tsx
import { Field } from "@niama/ui-react/form/field";
import { useFieldContext } from "@niama/ui-react/hooks/form-context";
import { Textarea } from "@niama/ui-react/ui/textarea";

// MAIN ------------------------------------------------------------------------------------------------------------------------------------
export default function TextareaField({ label }: TextareaFieldProps) {
  const { handleBlur, handleChange, name, state } = useFieldContext<string>();

  return (
    <Field label={label}>
      {(isInvalid) => (
        <Textarea
          aria-invalid={isInvalid}
          id={name}
          onBlur={handleBlur}
          onChange={(e) => handleChange(e.target.value)}
          placeholder={label}
          value={state.value}
        />
      )}
    </Field>
  );
}
export type TextareaFieldProps = { label: string };
