// packages/ui-react/src/components/theme-switcher.tsx
import { themeStore, toggleThemeWithTransition } from "@niama/ui/theme";
import { getThemeSwitcherLabel, THEME_SWITCHER } from "@niama/ui/theme-switcher";
import { Button } from "@niama/ui-react/button";
import { useSelector } from "@tanstack/react-store";
import { useRef } from "react";

// MAIN ------------------------------------------------------------------------------------------------------------------------------------
export function ThemeSwitcher() {
  const ref = useRef<HTMLButtonElement>(null);
  const theme = useSelector(themeStore);
  const label = getThemeSwitcherLabel(theme);

  const handleClick = () => toggleThemeWithTransition(ref.current);

  return (
    <Button
      aria-label={label}
      aria-pressed={theme === "dark"}
      className={THEME_SWITCHER.base()}
      onClick={handleClick}
      ref={ref}
      size="icon"
      suppressHydrationWarning
      title={label}
      type="button"
      variant="outline"
    >
      <span className={THEME_SWITCHER.sun()} />
      <span className={THEME_SWITCHER.moon()} />
      <span className="sr-only">{label}</span>
    </Button>
  );
}

// packages/ui-svelte/src/components/theme-switcher/theme-switcher.svelte
<script lang="ts">
  import { themeStore, toggleThemeWithTransition } from "@niama/ui/theme";
  import { getThemeSwitcherLabel, THEME_SWITCHER } from "@niama/ui/theme-switcher";
  import { Button } from "@niama/ui-svelte/button";
  import { useSelector as readStore } from "@tanstack/svelte-store";

  let ref = $state<HTMLButtonElement | null>(null);

  const theme = readStore(themeStore);
  const label = $derived(getThemeSwitcherLabel(theme.current));
</script>

<Button
  aria-label={label}
  aria-pressed={theme.current === "dark"}
  bind:ref
  class={THEME_SWITCHER.base()}
  onclick={() => toggleThemeWithTransition(ref)}
  size="icon"
  title={label}
  type="button"
  variant="outline"
>
  <span class={THEME_SWITCHER.sun()}></span>
  <span class={THEME_SWITCHER.moon()}></span>
  <span class="sr-only">{label}</span>
</Button>
