// packages/ui-solid/src/components/ui/sonner.tsx
import { useColorMode } from "@niama/ui-solid/ui/color-mode";
import { CircleCheck, Info, LoaderCircle, OctagonX, TriangleAlert } from "lucide-solid";
import type { Component, ComponentProps, JSX } from "solid-js";
import { Toaster as Sonner } from "solid-sonner";

type ToasterProps = ComponentProps<typeof Sonner>;

const Toaster: Component<ToasterProps> = (props) => {
  const { colorMode } = useColorMode();
  return (
    <Sonner
      class="toaster group"
      icons={{
        success: <CircleCheck class="size-4" />,
        info: <Info class="size-4" />,
        warning: <TriangleAlert class="size-4" />,
        error: <OctagonX class="size-4" />,
        loading: <LoaderCircle class="size-4 animate-spin" />,
      }}
      position="top-center"
      style={
        {
          "--normal-bg": "var(--popover)",
          "--normal-text": "var(--popover-foreground)",
          "--normal-border": "var(--border)",
          "--border-radius": "var(--radius)",
        } as JSX.CSSProperties
      }
      theme={colorMode()}
      {...props}
    />
  );
};

export { Toaster };

// packages/ui-svelte/src/components/ui/sonner/sonner.svelte
<script lang="ts">
  import { IconAlertOctagon, IconAlertTriangle, IconCircleCheck, IconInfoCircle, IconLoader } from "@tabler/icons-svelte";
  import { mode } from "mode-watcher";
  import { Toaster as Sonner, type ToasterProps as SonnerProps } from "svelte-sonner";

  let { ...restProps }: SonnerProps = $props();
</script>

<Sonner
  theme={mode.current}
  class="toaster group"
  style="--normal-bg: var(--color-popover); --normal-text: var(--color-popover-foreground); --normal-border: var(--color-border);"
  {...restProps}
>
  {#snippet loadingIcon()}
    <IconLoader class="size-4 animate-spin" />
  {/snippet}
  {#snippet successIcon()}
    <IconCircleCheck class="size-4" />
  {/snippet}
  {#snippet errorIcon()}
    <IconAlertOctagon class="size-4" />
  {/snippet}
  {#snippet infoIcon()}
    <IconInfoCircle class="size-4" />
  {/snippet}
  {#snippet warningIcon()}
    <IconAlertTriangle class="size-4" />
  {/snippet}
</Sonner>
