// apps/astro-svelte/src/pages/index/_contact-form.svelte
<script lang="ts">
  import { actions } from "astro:actions";
  import { ContactForm as ContactFormNative } from "@niama/ui-svelte/contact-form";
  import { toast } from "svelte-sonner";
</script>

<ContactFormNative
  onSubmit={async (value) => {
    const { error } = await actions.contact.create(value);
    if (error) throw error;
  }}
  onSuccess={() => {
    toast.success("Succès", { description: "Merci de votre intérêt ! Nous reviendrons vers vous très bientôt." });
  }}
/>

// apps/astro/src/components/contact-form.tsx
import { actions } from "astro:actions";
import { toast } from "@niama/ui/astro/toast.ts";
import { ContactForm as ContactFormNative } from "@niama/ui/react/contact-form";

// MAIN ------------------------------------------------------------------------------------------------------------------------------------
export function ContactForm() {
  return (
    <ContactFormNative
      onSubmit={async (value) => {
        const { error } = await actions.contact.create(value);
        if (error) throw error;
      }}
      onSuccess={() => {
        toast.success("Succès", { description: "Merci de votre intérêt ! Nous reviendrons vers vous très bientôt." });
      }}
    />
  );
}
